/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "tsnet_jni.go"


#include <jni.h>
#include <stdlib.h>

static void callStatusCallback(JNIEnv *env, jobject callback, const char *statusStr) {
    jclass cbClass = (*env)->GetObjectClass(env, callback);
    jmethodID methodId = (*env)->GetMethodID(env, cbClass, "onStatusChanged", "(Ljava/lang/String;)V");
    if (methodId != NULL) {
        jstring jStatus = (*env)->NewStringUTF(env, statusStr);
        (*env)->CallVoidMethod(env, callback, methodId, jStatus);
        (*env)->DeleteLocalRef(env, jStatus);
    }
}

static JavaVM *g_vm = NULL;
static jobject g_callback = NULL;

static void initVM(JNIEnv *env, jobject callback) {
    (*env)->GetJavaVM(env, &g_vm);
    if (g_callback != NULL) {
        (*env)->DeleteGlobalRef(env, g_callback);
    }
    g_callback = (*env)->NewGlobalRef(env, callback);
}

static void clearVM(JNIEnv *env) {
    if (g_callback != NULL) {
        (*env)->DeleteGlobalRef(env, g_callback);
        g_callback = NULL;
    }
}

static void notifyStatus(const char *statusStr) {
    if (g_vm == NULL || g_callback == NULL) return;
    JNIEnv *env = NULL;
    int attached = 0;
    int getEnvStat = (*g_vm)->GetEnv(g_vm, (void **)&env, JNI_VERSION_1_6);
    if (getEnvStat == JNI_EDETACHED) {
        #ifdef __ANDROID__
        if ((*g_vm)->AttachCurrentThread(g_vm, &env, NULL) == 0) {
            attached = 1;
        }
        #else
        if ((*g_vm)->AttachCurrentThread(g_vm, (void **)&env, NULL) == 0) {
            attached = 1;
        }
        #endif
    }
    if (env != NULL) {
        callStatusCallback(env, g_callback, statusStr);
        if (attached) {
            (*g_vm)->DetachCurrentThread(g_vm);
        }
    }
}

static const char* getStringChars(JNIEnv *env, jstring jstr) {
    if (jstr == NULL) return NULL;
    return (*env)->GetStringUTFChars(env, jstr, NULL);
}

static void releaseStringChars(JNIEnv *env, jstring jstr, const char* chars) {
    if (jstr != NULL && chars != NULL) {
        (*env)->ReleaseStringUTFChars(env, jstr, chars);
    }
}

#include <android/log.h>

static void goLog(const char* msg) {
    __android_log_write(ANDROID_LOG_DEBUG, "TsnetGo", msg);
}

static int isNull(JNIEnv *env, jobject obj) {
    return obj == NULL;
}


#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern jint Java_io_github_runc0derun_watcharr_shared_playback_TsnetManager_nativeStart(JNIEnv* env, jclass clazz, jstring jAuthKey, jstring jStateDir, jobject jCallback);
extern void Java_io_github_runc0derun_watcharr_shared_playback_TsnetManager_nativeStop(JNIEnv* env, jclass clazz);

#ifdef __cplusplus
}
#endif
